### ISSUE TITLE
Possible bdg-formats seq-dict related bug

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/mango#144]
There is possibility that the upgrade earlier today of bdg-formats and ADAM isn't playing nicely in Mango, though I am still looking into other causes for the error I see.  I'm trying to run:

```
mango-submit --master yarn-client -- hdfs://myhost:8020/user/jpaschall/mangotest1/orig_data/mm10_chrM.fa \
-read_files hdfs://myhost:8020/user/jpaschall/mangotest1/adam_data1/mouse_chrM.adam \
-feat_file hdfs://myhost:8020/user/jpaschall/mangotest1/orig_data/smalltest.bed
```
after generating the `mouse_chrM.adam` file with the current version ADAM master branch `7823abdb0`
and am getting:

```

java.lang.IllegalArgumentException: requirement failed: To generate SequenceDictionary on remote cluster, must use adam files
16/04/06 22:00:40 INFO VizReads: Overall Duration: 7.87 secs
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: To generate SequenceDictionary on remote cluster, must use adam files
	at org.bdgenomics.mango.models.ReferenceRDD.setSequenceDictionary(ReferenceRDD.scala:64)
	at org.bdgenomics.mango.models.ReferenceRDD.<init>(ReferenceRDD.scala:37)
	at org.bdgenomics.mango.cli.VizReads.run(VizReads.scala:452)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:54)
	at org.bdgenomics.mango.cli.VizReads.run(VizReads.scala:435)
	at org.bdgenomics.utils.cli.BDGCommandCompanion$class.main(BDGCommand.scala:32)
	at org.bdgenomics.mango.cli.VizReads$.main(VizReads.scala:66)
	at org.bdgenomics.mango.cli.VizReads.main(VizReads.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```
I'm trying again now with versions of mango and ADAM prior to the bdg-formats version bump, as these worked for me yesterday

**Comment by erictu** [comment]
I've logged an issue in Adam corresponding to the recent changes in adam. I
have a branch called kryo that contains the necessary patch to get it
working. Hope that helps!

**Comment by erictu** [comment]
I think I actually have have misread the issue. I think this exception is unrelated to the errors from the recent changes from adam. 

For this issue, we only support loading the reference from adam files on remote file systems, because we can only generate the sequence dictionary on remote file systems when in adam format. Because of the apis in htsjdk, generating sequence dictionaries from fasta only works on local file systems.

**Comment by jpdna** [comment]
Thanks Eric - but I'm not clear then on what exactly the current requirement is that you are describing for local vs. remote filesystem.  I assume the adam reads file should definitely be on hdfs.  What changes do I need to make to my attempt to do?:
```
mango-submit --master yarn-client -- hdfs://myhost:8020/user/jpaschall/mangotest1/orig_data/mm10_chrM.fa \
-read_files hdfs://myhost:8020/user/jpaschall/mangotest1/adam_data1/mouse_chrM.adam \
-feat_file hdfs://myhost:8020/user/jpaschall/mangotest1/orig_data/smalltest.bed
```

**Comment by erictu** [comment]
I would convert the mm10_chrM.fa file to adam format, then try rerunning it.

**Comment by jpdna** [comment]
> have a branch called kryo

@erictu , so hopefully your `kryo`  branch will not be needed anymore once:
https://github.com/bigdatagenomics/adam/pull/992
is merged, please try it out and feedback if not

**Comment by erictu** [comment]
Yeah no worries I just tested it it works great! I just needed to replace contig with contigName. I'll issue the patch soon.
