### ISSUE TITLE
Server Error 500 in Front End

### ISSUE THREAD

**Issue by Georgehe4** [bigdatagenomics/mango#234]
Reproduce: Load any read file, open up mango. View console if reads do not load.
java.lang.AssertionError: assertion failed: Timer name from on top of stack [/GET variants(19,false)] did not match passed-in timer name [GET reads]
	at scala.Predef$.assert(Predef.scala:179)
	at org.bdgenomics.utils.instrumentation.MetricsRecorder.finishPhase(MetricsRecorder.scala:55)
	at org.apache.spark.rdd.Timer$$anonfun$time$1.apply(Timer.scala:54)
	at org.apache.spark.rdd.Timer$$anonfun$time$1.apply(Timer.scala:48)
	at scala.Option.fold(Option.scala:157)
	at org.apache.spark.rdd.Timer.time(Timer.scala:48)
	at org.bdgenomics.mango.cli.VizServlet$$anonfun$12.apply(VizReads.scala:308)
	at org.bdgenomics.mango.cli.VizServlet$$anonfun$12.apply(VizReads.scala:308)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:285)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
	at org.scalatra.ScalatraBase$class.withRouteMultiParams(ScalatraBase.scala:356)
	at org.bdgenomics.mango.cli.VizServlet.withRouteMultiParams(VizReads.scala:211)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:278)
	at org.bdgenomics.mango.cli.VizServlet.invoke(VizReads.scala:211)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:253)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:251)
	at scala.Option.flatMap(Option.scala:170)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:251)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:250)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:446)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:250)
	at org.bdgenomics.mango.cli.VizServlet.runRoutes(VizReads.scala:211)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
	at org.bdgenomics.mango.cli.VizServlet.executeRoutes(VizReads.scala:211)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
	at org.bdgenomics.mango.cli.VizServlet.withResponse(VizReads.scala:211)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at org.bdgenomics.mango.cli.VizServlet.withRequest(VizReads.scala:211)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
	at org.bdgenomics.mango.cli.VizServlet.withRequestResponse(VizReads.scala:211)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
	at org.bdgenomics.mango.cli.VizServlet.org$scalatra$servlet$ServletBase$$super$handle(VizReads.scala:211)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
	at org.bdgenomics.mango.cli.VizServlet.handle(VizReads.scala:211)
	at org.scalatra.ScalatraServlet$class.service(ScalatraServlet.scala:60)
	at org.bdgenomics.mango.cli.VizServlet.service(VizReads.scala:211)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:479)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:521)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:910)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)

**Comment by akmorrow13** [comment]
this is a repeat of https://github.com/bigdatagenomics/utils/issues/65
