### ISSUE TITLE
missing an output location for shuffle 1

### ISSUE THREAD

**Issue by shibuvp** [bigdatagenomics/mango#300]
this is my mango-submit command
./bin/mango-submit --master yarn-client --driver-memory 2g --executor-memory 6g -- file:///opt/mango/example-files/hg19.fa -genes http://www.biodalliance.org/datasets/ensGene.bb -reads hdfs://master.hdp:8020/opt/ALL.chr17.7500000-7515000.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.adam -variants hdfs://master.hdp:8020/opt/ALL.chr17.7500000-7515000.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf -show_genotypes -discover -port 8082
the reference genome hg19.fa has size of 3.14GB
.vcf file has size of 91 kb
the yarn UI shows the program has been completed successfully, but i couldn't get any visualization
it shows the error "missing an output location for shuffle 1"
so i increased spark executor memory into 6gb (7gb max.)
but the error is same

**Comment by akmorrow13** [comment]
Where does this error appear? In the Mango browser?

**Comment by shibuvp** [comment]
@akmorrow13  , No, it is appears in shell while submitting the program

**Comment by akmorrow13** [comment]
Can you give a screenshot of where this is happening?

**Comment by shibuvp** [comment]
ok , i 'll

**Comment by shibuvp** [comment]
sorry for late responding, i was checking that error closely,i could restart the cluster, now i didn't get that error. But the program takes too much time to complete, i think it is because of  larger executor memory. 
Now the problem is the port 8082 doesn't shows proper visuals of varients

![capture111](https://user-images.githubusercontent.com/25296847/27021647-6f546b22-4f67-11e7-9325-4938dbc446be.JPG)

**Comment by akmorrow13** [comment]
I see. Depending on the dataset size and executor count, the first call can take some time to do initial collection.  In the Spark UI, does it show that these jobs are ever completing?

**Comment by shibuvp** [comment]
@akmorrow13  no it doesn't complete. we can only abort the job.

**Comment by akmorrow13** [comment]
@shibuvp please post the errors from the Spark UI, or what stages it is stuck on

**Comment by shibuvp** [comment]
17/06/13 09:42:06 INFO ContainerManagementProtocolProxy: Opening proxy : slave.hdp:45454
17/06/13 09:42:06 INFO ContainerManagementProtocolProxy: Opening proxy : slave3.hdp:45454
Exception in thread "ContainerLauncher-1" java.lang.Error: org.apache.spark.SparkException: Exception while starting container container_e87_1497240326879_0030_01_000004 on host slave3.hdp
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Exception while starting container container_e87_1497240326879_0030_01_000004 on host slave3.hdp
	at org.apache.spark.deploy.yarn.ExecutorRunnable.startContainer(ExecutorRunnable.scala:125)
	at org.apache.spark.deploy.yarn.ExecutorRunnable.run(ExecutorRunnable.scala:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	... 2 more
Caused by: org.apache.hadoop.yarn.exceptions.YarnException: Unauthorized request to start container. 
This token is expired. current time is 1497346893379 found 1497327726710
Note: System times on machines may be out of sync. Check system time and time zones.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.yarn.api.records.impl.pb.SerializedExceptionPBImpl.instantiateException(SerializedExceptionPBImpl.java:168)
	at org.apache.hadoop.yarn.api.records.impl.pb.SerializedExceptionPBImpl.deSerialize(SerializedExceptionPBImpl.java:106)
	at org.apache.hadoop.yarn.client.api.impl.NMClientImpl.startContainer(NMClientImpl.java:208)
	at org.apache.spark.deploy.yarn.ExecutorRunnable.startContainer(ExecutorRunnable.scala:122)
	... 4 more

**Comment by shibuvp** [comment]
what does mean Unauthorized request to start container.?

**Comment by akmorrow13** [comment]
This is not a Mango specific issue, but a yarn configuration issue, so changing your mango-submit parameters will not solve the issue. It's hard to say without being able to access yarn cluster, but from googling it, many people have associated this issue with node timezones: https://stackoverflow.com/questions/20257878/yarnexception-unauthorized-request-to-start-container

**Comment by shibuvp** [comment]
@akmorrow13  thanks .is it true that, each vcf file has each range to show variants?  i could found variants in the range of "7506407-7514599"  when using hg19.17.2bit reference genome.but it is not able to see when using chr18, chr15, chr14 etc
![c](https://user-images.githubusercontent.com/25296847/27117941-904a4672-50f6-11e7-9f4d-670944d10349.png)

**Comment by akmorrow13** [comment]
If you are using the test files, they only have data for chr 17. I am closing this issue as it seems things are working!
