### ISSUE TITLE
Run example failed

### ISSUE THREAD

**Issue by KingofCatfish** [bigdatagenomics/mango#301]
After successfully installed ADAM and Mango by maven, I failed to execute the sample program

 './example-files/run-example.sh'

The error goes like:

Using SPARK_SUBMIT=/usr/lib/spark-current/bin/spark-submit
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.bdgenomics.mango.cli.VizReads.<init>(VizReads.scala:626)
	at org.bdgenomics.mango.cli.VizReads$.apply(VizReads.scala:193)
	at org.bdgenomics.utils.cli.BDGCommandCompanion$class.main(BDGCommand.scala:33)
	at org.bdgenomics.mango.cli.VizReads$.main(VizReads.scala:122)
	at org.bdgenomics.mango.cli.VizReads.main(VizReads.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

I have correctly set $HADOOP_HOME, $HADOOP_CONF_DIR and uploaded 'example-files' folder to HDFS. 

Could anyone help me with this problem? Thanks in advance.

**Comment by akmorrow13** [comment]
This is a Spark issue, not Mango issue because SPARK-SUBMIT is broken. I would try rebuilding SPARK and making sure you only have 1 version.

**Comment by KingofCatfish** [comment]
I use spark 2.1.1, would it be the problem? In the pom.xml, the spark version is set to 1.6.3. I reinstall mango after changing this to <spark.version>2.1.1</spark.version> but I still failed to run the demo with the same error. Does mango support Spark 2.x?

**Comment by KingofCatfish** [comment]
I solved this, since I use spark 2.1.1, I should run ./scripts/move_to_spark_2.sh before installation.

Thanks to akmorrow13.

**Comment by akmorrow13** [comment]
Great to hear @KingofCatfish !
