### ISSUE TITLE
Visualize multiple tracks using BED files

### ISSUE THREAD

**Issue by SatyaGsk** [bigdatagenomics/mango#474]
Can someone help me with syntax and procedure to visualize multiple tracks using BED file with mango-submit command.

**Comment by SatyaGsk** [comment]
I am using mango-distribution-0.0.1 on Hadoop 2.6.0-cdh5.14.4/spark version 2.2.0/Scala version 2.11.8
my request is more of usage question how can we view multiple tracks using BED files. what mango-submit command should look like in this case.

**Comment by akmorrow13** [comment]
You can comma delim multiple bed files in the mango-submit command, like

`./mango-submit <path_to_reference> -features bed_file1,bed_file2 `

**Comment by SatyaGsk** [comment]
I am trying to use multiple BED file but i am getting empty tracks a s shown below. There are no error message on the spark terminal as well 

/home/smXXXXX/mango-distribution-0.0.1//bin/mango-submit --packages org.apache.parquet:parquet-hadoop:1.8.2 --  /home/gmdXXXXX/workspace/mango_testing/mango_test_files//hg19.2bit -port 3333  
-genes /home/gmdXXXXX/workspace/mango_testing/mango_test_files//ensGene.bb  
-features /home/gmdXXXXX/workspace/mango_testing/mango_test_files//gtex_gene_expression.bed,
/home/gmdXXXXX/workspace/mango_testing/mango_test_files//ucsc_genes_hg19.bed

Attached is the screen shot and terminal output.


![gb1](https://user-images.githubusercontent.com/44622748/50089224-1a3bef80-01fd-11e9-90d9-8b612006dddd.png)
[teminal.txt](https://github.com/bigdatagenomics/mango/files/2686137/teminal.txt)

**Comment by akmorrow13** [comment]
@SatyaGsk there does not seem to be any errors. There is a note in the UI saying "Loading Features" Can you please check the Spark UI to make sure that Spark is indeed still running a task to load the features? If the Spark UI is indeed running no tasks, right click in the browser and report any javascript errors.

**Comment by SatyaGsk** [comment]
Exactly my point the spark job is running fine and does not show any errors and we can not see the tracks even after 10 min. Is there a way we can bump up the log level to see any application messages.

**Comment by akmorrow13** [comment]
So to clarify, the Spark job has not failed?

**Comment by akmorrow13** [comment]
To see any additional Spark information, you would have to configure the log4j properties file, as required by Spark. [This page describes log4j in regards to Spark.](http://spark.apache.org/docs/latest/configuration.html#configuring-logging), and explains how to set up a log4j properties file. What are the bed file sizes you are running on?

**Comment by SatyaGsk** [comment]
Wish you happy new year!
Does Mango support only certain type of BED files I am getting Number format exception when loading the features.

Mango command
/home/sm/mango-distribution-0.0.1//bin/mango-submit --packages org.apache.parquet:parquet-hadoop:1.8.2 --  /home/gm/workspace/mango_testing/mango_test_files//hg19.2bit -port 3333  -genes /home/gm/workspace/mango_testing/mango_test_files//ensGene.bb  -features /user/gm/workspace/mango_testing/mango_test_files//gtex_gene_expression.bed,/user/gm/workspace/mango_testing/mango_test_files//ucsc_genes_hg19.bed

Error message:
The error message:
10:50:02 INFO scheduler.DAGScheduler: ShuffleMapStage 2 (map at LazyMaterialization.scala:311) failed in 0.203 s due to Job aborted due to stage failure: Task 2 in stage 2.0 failed 4 times, most recent failure: Lost task 2.3 in stage 2.0 (TID 16, bluedata752.corpnet3.com, executor 1): java.lang.NumberFormatException: For input string: "+"
                at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
                at java.lang.Long.parseLong(Long.java:581)
                at java.lang.Long
parseLong(Long.java:631)
                at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:276)
                at scala.collection.immutable.StringOps.toLong(StringOps.scala:29)
                at org.bdgenomics.adam.rdd.feature.BEDParser.parse(FeatureParser.scala:322)
                at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadBed$1$$anonfun$29.apply(ADAMContext.scala:2688)
                at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadBed$1$$anonfun$29.apply(ADAMContext.scala:2688)
                at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
                at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
                at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
                at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
                at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
                at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
                at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
                at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
                at org.apache.spark.scheduler.Task.run(Task.scala:108)
                at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

**Comment by akmorrow13** [comment]
It looks like this is a loadBed issue in ADAM. See the error:
`
org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadBed$1$$anonfun$29.apply(ADAMContext.scala:2688)
`

Do you have a sample of the bed file you can attach?

**Comment by SatyaGsk** [comment]
Enclosed is the bed files for the mango submit command provided earlier. Let me know if you need other files as well like vcf and bb

[bedZip.zip](https://github.com/bigdatagenomics/mango/files/2747281/bedZip.zip)

**Comment by akmorrow13** [comment]
ucsc_genes_hg19.bed is not a valid bed file. [You can find the BED file formatting specifications here](https://genome.ucsc.edu/FAQ/FAQformat.html#format1). Once you format it as a valid bed file it should work. gtex_gene_expression.bed is valid.
