### ISSUE TITLE
GA4GH converter throws error

### ISSUE THREAD

**Issue by rl1m** [bigdatagenomics/mango#475]
Halo,

I was trying to run the examples at https://github.com/bigdatagenomics/mango/blob/master/example-files/notebooks/mango-viz.ipynb with `pyspark`. Unfortunately it throws the following error (below):

Here was the command:
```
# spark version: 2.3.2-bin-hadoop2.7
pyspark --jars /~/programs/mango/mango-assembly/target/mango-assembly-0.0.3-SNAPSHOT.jar \
--driver-class-path /~/programs/mango/mango-assembly/target/mango-assembly-0.0.3-SNAPSHOT.jar
```

The error:
```
Py4JError: An error occurred while calling z:org.bdgenomics.mango.converters.GA4GHutil.alignmentRecordRDDtoJSON. Trace:
py4j.Py4JException: Method alignmentRecordRDDtoJSON([class org.bdgenomics.adam.rdd.read.DatasetBoundAlignmentRecordRDD]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:339)
	at py4j.Gateway.invoke(Gateway.java:276)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

Could you provide any pointers to solve this issue, please?

Thanks in advance and look forward to hearing from you.

Cheers!

RL

**Comment by akmorrow13** [comment]
The Mango notebooks are intended to be run with the `./bin/mango-notebook` command. This file will set up the required jars. Let me know if that works!

**Comment by rl1m** [comment]
Aha.. Thanks for the pointer. Now it works :)

This is the following command to solve the Py4JException:
```
# spark version: 2.3.2-bin-hadoop2.7
pyspark --conf spark.serializer=org.apache.spark.serializer.KryoSerializer\
  --conf spark.kryo.registrator=org.bdgenomics.mango.serialization.MangoKryoRegistrator\
  --jars ~/programs/mango/mango-assembly/target/mango-assembly-0.0.3-SNAPSHOT.jar\    
  --driver-class-path ~/programs/mango/mango-assembly/target/mango-assembly-0.0.3-SNAPSHOT.jar
```

Cheers and have a nice day!
