### ISSUE TITLE
mango-viz fails to build on miniconda2

### ISSUE THREAD

**Issue by erictu** [bigdatagenomics/mango#523]
Following Python bindings setup: https://bdg-mango.readthedocs.io/en/latest/installation/source.html#python

When running `make prepare` in the `mango-viz` directory, the following build error occurs:
```
> node lib/install.js

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/mango/mango-viz/bdgenomics/mango/js/node_modules/natives/index.js:143:24)
    at Object.req [as require] (mango/mango-viz/bdgenomics/mango/js/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/mango/mango-viz/bdgenomics/mango/js/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
```
npm: 6.10.0
node: 12.5.0
Python: clean miniconda2 (Python 2.7)
Mac OS 10.14.3

**Comment by akmorrow13** [comment]
We no longer support python 2.7 due to Modin dependency limitations. Python 2 is also being dropped in January.
