### ISSUE TITLE
pip `v20` AttributeError: 'ParsedRequirement' object has no attribute 'req'

### ISSUE THREAD

**Issue by ricky-lim** [bigdatagenomics/mango#575]
` python -m pip install bdgenomics.mango.pileup` generates the following Error:

```
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o6qkx7rm/bdgenomics.mango.pileup/setup.py", line 36, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-install-o6qkx7rm/bdgenomics.mango.pileup/setup.py", line 36, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

With pip v20, it seems the internal API has changed.

**Comment by akmorrow13** [comment]
Thanks for bringing this to our attention @ricky-lim. I will drop a new release in the next day or so that fixes this and ping you then. The quickest fix is to use pip=19.3.1 in the meantime.
